### ISSUE TITLE
Not able to access the endpoints 

### ISSUE THREAD

**Issue by doaa-khaled** [snowdrop/vertx-spring-boot#103]
Hi All, 
I am new in vertx, I established spring config server and need to integrate with vertx, I did it but now I want to reload the configuration at runtime with changes.
I exposed that I will be able to do that by adding this dependency, but I always get 404 http status
I am sure there is something wrong from myside, I added the dependency :
<dependency>
      <groupId>dev.snowdrop</groupId>
      <artifactId>vertx-spring-boot-starter-actuator</artifactId>
      <version>1.2.1</version>
</dependency>

and this configuration in application.properties:
management.server.port=8081
management.endpoints.web.exposure.include=*

and used this URL (post method):
http://localhost:8081/actuator/refresh

appreciate ur support

**Comment by aureamunoz** [comment]
Hello @doaa-khaled 

Could  you please try with http://localhost:8081/actuator/health and let us know?

Thanks

**Comment by aureamunoz** [comment]
Not having any news, I close this ticket, feel free to re-open it if you have still any problem
