### ISSUE TITLE
Discuss the next steps for the Vert.x Spring Boot

### ISSUE THREAD

**Issue by gytis** [snowdrop/vertx-spring-boot#47]
Since all the WebFlux related components were released as GA it's time to discuss the possible future development options.

## GA with 2.3.0 Snowdrop release (already implemented but need more testing and documentation)

- [ ] Vert.x Spring Boot Kafka
- [ ] Vert.x Spring Boot AMQP
- [ ] Vert.x Spring Boot Mail

## New components to consider (not implemented)

- [ ] Postgres and MySQL Vert.x client integration into R2DBC
- [ ] Vert.x event bus integration into Spring Integration
- [ ] Vert.x event bus integration into Spring Cloud Stream

**Comment by gytis** [comment]
cc @cmoulliard @nainaz @zekaguilar

**Comment by cmoulliard** [comment]
Can you use checkboxes to list the components to consider ? @gytis

**Comment by gytis** [comment]
As agreed in the grooming call we will productise Kafka, AMQP and Mail (if we'll manage to squeeze it in). R2DBC could be the next release deliverable.

**Comment by zekaguilar** [comment]
Should I create the JIRA Issue for the next release @gytis ? Or not for now

**Comment by gytis** [comment]
For R2DBC?

**Comment by zekaguilar** [comment]
yes

**Comment by gytis** [comment]
Maybe let's wait for the grooming session for the next release. If we agree to do it then, then we'll create a JIRA for it.

**Comment by zekaguilar** [comment]
Ok, Thanks !
