### ISSUE TITLE
NullPointerException with 1.2.0 version of vertx-spring-boot-starter-http and Spring Boot 2.5.4

### ISSUE THREAD

**Issue by niushapaks** [snowdrop/vertx-spring-boot#99]
Hi guys, I've got this error while sending a GET request to my sample application :

```
2021-08-31 10:59:14.036 ERROR 45489 --- [ntloop-thread-1] io.vertx.core.impl.ContextImpl           : Unhandled exception

java.lang.NullPointerException: cause
	at io.netty.util.internal.ObjectUtil.checkNotNull(ObjectUtil.java:39) ~[netty-common-4.1.67.Final.jar:4.1.67.Final]
```

Here are my parent and key dependencies :

```
[...]
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.5.4</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>

[...]
	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-webflux</artifactId>
		</dependency>

		<dependency>
			<groupId>dev.snowdrop</groupId>
			<artifactId>vertx-spring-boot-starter-http</artifactId>
			<version>1.1.6</version>
		</dependency>
[...]
```

This seems to be linked to this issue : https://github.com/TNG/keycloak-mock/issues/74

It works well with **1.1.6** version of vertx-spring-boot-starter-http

**Comment by jacobdotcosta** [comment]
Hi. 

We're releasing `1.2.1` that should fix this problem, by updating Vert.x to version `3.9.8` (check PR #98 ).

**Comment by jacobdotcosta** [comment]
Version `1.2.1`has been release. Could you retest using this version? @niushapaks

**Comment by niushapaks** [comment]
Although I'm not able to reproduce the problem with 1.2.0 (maybe a sub dependency also upgraded netty / vert.x), It works well with version 1.2.1, thanks !
